# Generated by Django 4.2.4 on 2023-08-19 13:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('product', 'user')},
        ),
    ]
